### ISSUE TITLE
Question and a possible suggestion on Crawljobs 

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#3]
I ran the latest code and noticed that at one point we had:
 - 334 total jobs and;
 - (only) 11 finished jobs

I don't know how Python or this script handle parallel processing, but if we are having such a big backlog we should probably stop scheduling jobs say after we have 50 jobs already queued. 

if the queue is just a DB entry and worker threads just pick and process one at a time, then it's fine to keep making DB entries.

**Comment by kvahuja** [comment]
i noticed that jobs completion is random, I speculate that this would impact how we are saving data into DB. just thinking if we have to / should handle jobs in order of date. I worry that if we don't, we will have match's history in random order.

or is there a way to "sort" matches in order of when they were played?

**Comment by schneefux** [comment]
If a job did not return data, it stays unfinished, but it is not being processed. It is a workaround because the API does not return live data (yet), for example querying 8:00 to 8:30 will not return data at 8:30, but it will return data four hours later. (Basically a temporary fix for #6.)
There was a line `"DELETE FROM crawljobs WHERE finished=false"` to retry unfinished jobs if the application is restarted, but [I commented it out](https://github.com/vainglorygame/apigrabber/blob/master/api.py#L225) for development.

Completion happens from the beginning of the most recent job that has no job directly before it backwards to the oldest job.
The table is initialized with a completed job from `Feb 1 00:00` - `Feb 1 00:00` and a completed job from `startup timestamp` - `startup timestamp` (#5), so a worker A picks up a job that ends at `startup timestamp`, another picks up the job before A's job, … until there are no more jobs.
An update request inserts a job from `now` - `now`, and a worker (or multiple) will pick up the job before `now` to fill the gap.

`match` objects always have `attributes->>'createdAt'` so it can be ordered later.

**Comment by kvahuja** [comment]
ok sounds good.

dont delete crawl jobs from the JOb so keep the following commented for good or better delete it. we will archive DB records through a global archival process.

```
DELETE FROM crawljobs WHERE finished=false
```

**Comment by schneefux** [comment]
#39
